version: "3"
services:
  pdns:
    build: .
    container_name: pdns
    ports:
    - "53:53"
    - "53:53/udp"
    - "36000:8081"
    env_file: .env.master

  pdns-db:
    image: mysql:5.7
    container_name: pdns_db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/pdns_data:/var/lib/mysql
    env_file: .env.master
